[project]
name = "pytorch-test-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "ruff>=0.13.0",
    "torch>=2.8.0",
]
